 

<table BORDER>
	<thead>
		<tr>
			<th>UE</th>
			<th>COEF</th>
			<th>Moyenne</th>
			<th>Credit Acquis</th>
			<th>ECUE</th>
			<th>COEF</th>
			<th>DS1</th>
			<th>DS2</th>
			<th>AA</th>
			<th>Moyenne</th>
			<th>Credit Acquis</th>
		<tr>
	</thead>
	<tbody>
	
		<tr >
			<td rowspan="4">{UE1:@Value}</td>
			<td rowspan="4">{COEFUE1:@Value}</td>			
			<td rowspan="4">{MoyenneUE1:@Value}</td>
			<td rowspan="4">{CREDITUE1:@Value}</td>
		</tr>
		<tr>	
			<td>{ECUE1:@Value}</td>
			<td>{COEFECUE1:@Value}</td>
			<td>{DS1ECUE1:@Value}</td>
			<td>{DS2ECUE1:@Value}</td>
			<td>{AAECUE1:@Value}</td>
			<td>{MoyenneECUE1:@Value}</td>
			<td>{CREDITECUE1:@Value}</td>
		<tr>
		<tr>	
			<td>{ECUE2:@Value}</td>
			<td>{COEFECUE2:@Value}</td>
			<td>{DS1ECUE2:@Value}</td>
			<td>{DS2ECUE2:@Value}</td>
			<td>{AAECUE2:@Value}</td>
			<td>{MoyenneECUE2:@Value}</td>
			<td>{CREDITECUE2:@Value}</td>
		<tr>
	
	</tbody>
</table>

